# Generated by Django 5.2.11 on 2026-02-24 14:32

import localized_fields.fields.char_field
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tile",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=4, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("suit", models.CharField(max_length=20)),
                ("rank", models.IntegerField(blank=True, null=True)),
                (
                    "label",
                    localized_fields.fields.char_field.LocalizedCharField(
                        max_length=20, required=["en"]
                    ),
                ),
            ],
            options={
                "ordering": ["suit", "rank"],
            },
        ),
    ]
