# Generated by Django 5.2.11 on 2026-02-25 04:01

import django.db.models.deletion
import django.utils.timezone
import localized_fields.fields.char_field
import localized_fields.fields.text_field
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RuleDefinition",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("code", models.CharField(max_length=64, unique=True)),
                (
                    "label",
                    localized_fields.fields.char_field.LocalizedCharField(
                        required=["en"]
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("pattern", "PATTERN"),
                            ("bonus", "BONUS"),
                            ("limit", "LIMIT"),
                            ("special", "SPECIAL"),
                            ("dora_like", "DORA_LIKE"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "description",
                    localized_fields.fields.text_field.LocalizedTextField(
                        blank=True, required=[]
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="RuleLogic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "logic_type",
                    models.CharField(
                        choices=[
                            ("standard", "STANDARD"),
                            ("special_shape", "SPECIAL_SHAPE"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "combine_op",
                    models.CharField(
                        blank=True,
                        choices=[("and", "AND"), ("or", "OR")],
                        default="",
                        max_length=8,
                    ),
                ),
                ("min_match", models.IntegerField(blank=True, null=True)),
                ("note", models.TextField(blank=True, default="")),
                (
                    "rule_definition",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logic",
                        to="rule.ruledefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GroupCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "group_type",
                    models.CharField(
                        choices=[
                            ("chow", "CHOW"),
                            ("pung", "PUNG"),
                            ("kong", "KONG"),
                            ("pair", "PAIR"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("at_least", "AT_LEAST"),
                            ("exactly", "EXACTLY"),
                            ("not_exists", "NOT_EXISTS"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value_int", models.IntegerField(blank=True, null=True)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("tile", "TILE"),
                            ("tile_set", "TILE_SET"),
                            ("seat_wind", "SEAT_WIND"),
                            ("round_wind", "ROUND_WIND"),
                            ("any_honor", "ANY_HONOR"),
                            ("any_terminal", "ANY_TERMINAL"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "tile_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1B", "BAMBOO_1"),
                            ("2B", "BAMBOO_2"),
                            ("3B", "BAMBOO_3"),
                            ("4B", "BAMBOO_4"),
                            ("5B", "BAMBOO_5"),
                            ("6B", "BAMBOO_6"),
                            ("7B", "BAMBOO_7"),
                            ("8B", "BAMBOO_8"),
                            ("9B", "BAMBOO_9"),
                            ("1C", "CHARACTER_1"),
                            ("2C", "CHARACTER_2"),
                            ("3C", "CHARACTER_3"),
                            ("4C", "CHARACTER_4"),
                            ("5C", "CHARACTER_5"),
                            ("6C", "CHARACTER_6"),
                            ("7C", "CHARACTER_7"),
                            ("8C", "CHARACTER_8"),
                            ("9C", "CHARACTER_9"),
                            ("1D", "DOT_1"),
                            ("2D", "DOT_2"),
                            ("3D", "DOT_3"),
                            ("4D", "DOT_4"),
                            ("5D", "DOT_5"),
                            ("6D", "DOT_6"),
                            ("7D", "DOT_7"),
                            ("8D", "DOT_8"),
                            ("9D", "DOT_9"),
                            ("EW", "EAST_WIND"),
                            ("SW", "SOUTH_WIND"),
                            ("WW", "WEST_WIND"),
                            ("NW", "NORTH_WIND"),
                            ("RD", "RED_DRAGON"),
                            ("GD", "GREEN_DRAGON"),
                            ("WD", "WHITE_DRAGON"),
                            ("1F", "FLOWER_1"),
                            ("2F", "FLOWER_2"),
                            ("3F", "FLOWER_3"),
                            ("4F", "FLOWER_4"),
                            ("1S", "SEASON_1"),
                            ("2S", "SEASON_2"),
                            ("3S", "SEASON_3"),
                            ("4S", "SEASON_4"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "tile_set_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bamboo", "BAMBOO"),
                            ("character", "CHARACTER"),
                            ("dot", "DOT"),
                            ("winds", "WINDS"),
                            ("dragons", "DRAGONS"),
                            ("honors", "HONORS"),
                            ("terminals", "TERMINALS"),
                            ("simples", "SIMPLES"),
                            ("flowers", "FLOWERS"),
                            ("seasons", "SEASONS"),
                            ("bonus", "BONUS"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("allow_open", models.BooleanField(default=True)),
                ("allow_closed", models.BooleanField(default=True)),
                (
                    "rule_logic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_conditions",
                        to="rule.rulelogic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CountCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        choices=[("tile", "TILE"), ("tile_set", "TILE_SET")],
                        max_length=16,
                    ),
                ),
                (
                    "tile_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1B", "BAMBOO_1"),
                            ("2B", "BAMBOO_2"),
                            ("3B", "BAMBOO_3"),
                            ("4B", "BAMBOO_4"),
                            ("5B", "BAMBOO_5"),
                            ("6B", "BAMBOO_6"),
                            ("7B", "BAMBOO_7"),
                            ("8B", "BAMBOO_8"),
                            ("9B", "BAMBOO_9"),
                            ("1C", "CHARACTER_1"),
                            ("2C", "CHARACTER_2"),
                            ("3C", "CHARACTER_3"),
                            ("4C", "CHARACTER_4"),
                            ("5C", "CHARACTER_5"),
                            ("6C", "CHARACTER_6"),
                            ("7C", "CHARACTER_7"),
                            ("8C", "CHARACTER_8"),
                            ("9C", "CHARACTER_9"),
                            ("1D", "DOT_1"),
                            ("2D", "DOT_2"),
                            ("3D", "DOT_3"),
                            ("4D", "DOT_4"),
                            ("5D", "DOT_5"),
                            ("6D", "DOT_6"),
                            ("7D", "DOT_7"),
                            ("8D", "DOT_8"),
                            ("9D", "DOT_9"),
                            ("EW", "EAST_WIND"),
                            ("SW", "SOUTH_WIND"),
                            ("WW", "WEST_WIND"),
                            ("NW", "NORTH_WIND"),
                            ("RD", "RED_DRAGON"),
                            ("GD", "GREEN_DRAGON"),
                            ("WD", "WHITE_DRAGON"),
                            ("1F", "FLOWER_1"),
                            ("2F", "FLOWER_2"),
                            ("3F", "FLOWER_3"),
                            ("4F", "FLOWER_4"),
                            ("1S", "SEASON_1"),
                            ("2S", "SEASON_2"),
                            ("3S", "SEASON_3"),
                            ("4S", "SEASON_4"),
                        ],
                        max_length=4,
                        null=True,
                    ),
                ),
                (
                    "tile_set_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("bamboo", "BAMBOO"),
                            ("character", "CHARACTER"),
                            ("dot", "DOT"),
                            ("winds", "WINDS"),
                            ("dragons", "DRAGONS"),
                            ("honors", "HONORS"),
                            ("terminals", "TERMINALS"),
                            ("simples", "SIMPLES"),
                            ("flowers", "FLOWERS"),
                            ("seasons", "SEASONS"),
                            ("bonus", "BONUS"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[
                            ("at_least", "AT_LEAST"),
                            ("exactly", "EXACTLY"),
                            ("not_exists", "NOT_EXISTS"),
                        ],
                        max_length=16,
                    ),
                ),
                ("value_int", models.IntegerField()),
                (
                    "rule_logic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="count_conditions",
                        to="rule.rulelogic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContextCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "context_field",
                    models.CharField(
                        choices=[
                            ("win_source", "WIN_SOURCE"),
                            ("seat_wind", "SEAT_WIND"),
                            ("round_wind", "ROUND_WIND"),
                            ("is_open_hand", "IS_OPEN_HAND"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "operator",
                    models.CharField(
                        choices=[("equals", "EQUALS"), ("not_equals", "NOT_EQUALS")],
                        max_length=16,
                    ),
                ),
                ("value", models.CharField(max_length=32)),
                (
                    "rule_logic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="context_conditions",
                        to="rule.rulelogic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecialShapeCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "special_shape",
                    models.CharField(
                        choices=[
                            ("seven_pairs", "SEVEN_PAIRS"),
                            ("thirteen_orphans", "THIRTEEN_ORPHANS"),
                            ("nine_gates", "NINE_GATES"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "rule_logic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shape_conditions",
                        to="rule.rulelogic",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SuitCondition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "suit_constraint",
                    models.CharField(
                        choices=[
                            ("single_suit", "SINGLE_SUIT"),
                            ("single_suit_with_honors", "SINGLE_SUIT_WITH_HONORS"),
                            ("no_honors", "NO_HONORS"),
                            ("all_suits_required", "ALL_SUITS_REQUIRED"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "rule_logic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suit_conditions",
                        to="rule.rulelogic",
                    ),
                ),
            ],
        ),
    ]
