from django.db import migrations

RULES = [
    # --- LIMIT HANDS ---
    {
        'code': 'thirteen_orphans',
        'label': {
            'en': 'Thirteen Orphans',
            'zh-hk': '十三么',
            'zh-cn': '十三幺',
        },
        'kind': 'limit',
        'logic_type': 'special_shape',
        'combine_op': '',
        'note': '',
        'group_conditions': [],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [{'special_shape': 'thirteen_orphans'}],
        'count_conditions': [],
    },
    {
        'code': 'four_gongs',
        'label': {
            'en': 'Four Gongs',
            'zh-hk': '十八羅漢',
            'zh-cn': '四槓',
        },
        'kind': 'limit',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'kong',
                'operator': 'at_least',
                'value_int': 4,
                'target_type': 'tile',
                'tile_code': None,
                'tile_set_code': None,
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'big_four_wind',
        'label': {
            'en': 'Big Four Wind',
            'zh-hk': '大四喜',
            'zh-cn': '大四喜',
        },
        'kind': 'limit',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'pung',
                'operator': 'at_least',
                'value_int': 4,
                'target_type': 'tile_set',
                'tile_code': None,
                'tile_set_code': 'winds',
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'nine_gates',
        'label': {
            'en': 'Nine Gates',
            'zh-hk': '九蓮寶燈',
            'zh-cn': '九蓮寶燈',
        },
        'kind': 'limit',
        'logic_type': 'special_shape',
        'combine_op': '',
        'note': '',
        'group_conditions': [],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [{'special_shape': 'nine_gates'}],
        'count_conditions': [],
    },
    {
        'code': 'all_honours',
        'label': {
            'en': 'All Honours',
            'zh-hk': '字一色',
            'zh-cn': '字一色',
        },
        'kind': 'limit',
        'logic_type': 'standard',
        'combine_op': 'and',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'pung',
                'operator': 'at_least',
                'value_int': 4,
                'target_type': 'any_honor',
                'tile_code': None,
                'tile_set_code': None,
                'allow_open': True,
                'allow_closed': True,
            },
            {
                'group_type': 'pair',
                'operator': 'at_least',
                'value_int': 1,
                'target_type': 'any_honor',
                'tile_code': None,
                'tile_set_code': None,
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'all_terminals',
        'label': {
            'en': 'All Terminals',
            'zh-hk': '清老頭',
            'zh-cn': '清老頭',
        },
        'kind': 'limit',
        'logic_type': 'standard',
        'combine_op': 'and',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'pung',
                'operator': 'at_least',
                'value_int': 4,
                'target_type': 'any_terminal',
                'tile_code': None,
                'tile_set_code': None,
                'allow_open': True,
                'allow_closed': True,
            },
            {
                'group_type': 'pair',
                'operator': 'at_least',
                'value_int': 1,
                'target_type': 'any_terminal',
                'tile_code': None,
                'tile_set_code': None,
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'all_concealed_pongs',
        'label': {
            'en': 'All Concealed Pongs',
            'zh-hk': '四暗刻',
            'zh-cn': '四暗刻',
        },
        'kind': 'limit',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'pung',
                'operator': 'at_least',
                'value_int': 4,
                'target_type': 'tile',
                'tile_code': None,
                'tile_set_code': None,
                'allow_open': False,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'tsumo_after_double_kong',
        'label': {
            'en': 'Touch Myself After Double Gong',
            'zh-hk': '雙槓嶺上開花',
            'zh-cn': '雙槓嶺上開花',
        },
        'kind': 'limit',
        'logic_type': 'standard',
        'combine_op': 'and',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'kong',
                'operator': 'at_least',
                'value_int': 2,
                'target_type': 'tile',
                'tile_code': None,
                'tile_set_code': None,
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [
            {
                'context_field': 'win_source',
                'operator': 'equals',
                'value': 'self_draw',
            },
        ],
        'shape_conditions': [],
        'count_conditions': [],
    },
    # --- PATTERN HANDS ---
    {
        'code': 'seven_pairs',
        'label': {
            'en': 'Seven Pairs',
            'zh-hk': '七對子',
            'zh-cn': '七对子',
        },
        'kind': 'pattern',
        'logic_type': 'special_shape',
        'combine_op': '',
        'note': '',
        'group_conditions': [],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [{'special_shape': 'seven_pairs'}],
        'count_conditions': [],
    },
    {
        'code': 'big_three_dragons',
        'label': {
            'en': 'Big Three Dragons',
            'zh-hk': '大三元',
            'zh-cn': '大三元',
        },
        'kind': 'pattern',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'pung',
                'operator': 'at_least',
                'value_int': 3,
                'target_type': 'tile_set',
                'tile_code': None,
                'tile_set_code': 'dragons',
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'full_flush',
        'label': {
            'en': 'Full Flush',
            'zh-hk': '清一色',
            'zh-cn': '清一色',
        },
        'kind': 'pattern',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [],
        'suit_conditions': [{'suit_constraint': 'single_suit'}],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'little_four_wind',
        'label': {
            'en': 'Little Four Wind',
            'zh-hk': '小四喜',
            'zh-cn': '小四喜',
        },
        'kind': 'pattern',
        'logic_type': 'standard',
        'combine_op': 'and',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'pung',
                'operator': 'at_least',
                'value_int': 3,
                'target_type': 'tile_set',
                'tile_code': None,
                'tile_set_code': 'winds',
                'allow_open': True,
                'allow_closed': True,
            },
            {
                'group_type': 'pair',
                'operator': 'at_least',
                'value_int': 1,
                'target_type': 'tile_set',
                'tile_code': None,
                'tile_set_code': 'winds',
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'small_three_dragon',
        'label': {
            'en': 'Small Three Dragon',
            'zh-hk': '小三元',
            'zh-cn': '小三元',
        },
        'kind': 'pattern',
        'logic_type': 'standard',
        'combine_op': 'and',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'pung',
                'operator': 'at_least',
                'value_int': 2,
                'target_type': 'tile_set',
                'tile_code': None,
                'tile_set_code': 'dragons',
                'allow_open': True,
                'allow_closed': True,
            },
            {
                'group_type': 'pair',
                'operator': 'at_least',
                'value_int': 1,
                'target_type': 'tile_set',
                'tile_code': None,
                'tile_set_code': 'dragons',
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'half_flush',
        'label': {
            'en': 'Half Flush',
            'zh-hk': '混一色',
            'zh-cn': '混一色',
        },
        'kind': 'pattern',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [],
        'suit_conditions': [{'suit_constraint': 'single_suit_with_honors'}],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'all_pongs',
        'label': {
            'en': 'All Pongs',
            'zh-hk': '對對胡',
            'zh-cn': '碰碰胡',
        },
        'kind': 'pattern',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'pung',
                'operator': 'at_least',
                'value_int': 4,
                'target_type': 'tile',
                'tile_code': None,
                'tile_set_code': None,
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'all_chows',
        'label': {
            'en': 'All Chows',
            'zh-hk': '平胡',
            'zh-cn': '平和',
        },
        'kind': 'pattern',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'chow',
                'operator': 'at_least',
                'value_int': 4,
                'target_type': 'tile',
                'tile_code': None,
                'tile_set_code': None,
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'half_terminals',
        'label': {
            'en': 'Half Terminals',
            'zh-hk': '混老頭',
            'zh-cn': '混老頭',
        },
        'kind': 'pattern',
        'logic_type': 'compound',
        'combine_op': 'AND',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'pung',
                'operator': 'at_least',
                'value_int': 4,
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [
            {
                'target_type': 'tile_set',
                'tile_set_code': 'simples',
                'operator': 'exactly',
                'value_int': 0,
            },
        ],
    },
    # --- BONUS HANDS ---
    {
        'code': 'round_wind_pong',
        'label': {
            'en': 'Round Wind Pong',
            'zh-hk': '圈風刻',
            'zh-cn': '圈風刻',
        },
        'kind': 'bonus',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'pung',
                'operator': 'at_least',
                'value_int': 1,
                'target_type': 'round_wind',
                'tile_code': None,
                'tile_set_code': None,
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'seat_wind_pong',
        'label': {
            'en': 'Seat Wind Pong',
            'zh-hk': '門風刻',
            'zh-cn': '門風刻',
        },
        'kind': 'bonus',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'pung',
                'operator': 'at_least',
                'value_int': 1,
                'target_type': 'seat_wind',
                'tile_code': None,
                'tile_set_code': None,
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'red_dragon_pong',
        'label': {
            'en': 'Red Dragon Pong',
            'zh-hk': '中',
            'zh-cn': '紅中',
        },
        'kind': 'bonus',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'pung',
                'operator': 'at_least',
                'value_int': 1,
                'target_type': 'tile',
                'tile_code': 'RD',
                'tile_set_code': None,
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'green_dragon_pong',
        'label': {
            'en': 'Green Dragon Pong',
            'zh-hk': '發',
            'zh-cn': '發財',
        },
        'kind': 'bonus',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'pung',
                'operator': 'at_least',
                'value_int': 1,
                'target_type': 'tile',
                'tile_code': 'GD',
                'tile_set_code': None,
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'white_dragon_pong',
        'label': {
            'en': 'White Dragon Pong',
            'zh-hk': '白',
            'zh-cn': '白板',
        },
        'kind': 'bonus',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'pung',
                'operator': 'at_least',
                'value_int': 1,
                'target_type': 'tile',
                'tile_code': 'WD',
                'tile_set_code': None,
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    # --- SPECIAL / WIN CONDITION ---
    {
        'code': 'tsumo',
        'label': {
            'en': 'Touch Myself',
            'zh-hk': '自摸',
            'zh-cn': '自摸',
        },
        'kind': 'special',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [],
        'suit_conditions': [],
        'context_conditions': [
            {
                'context_field': 'win_source',
                'operator': 'equals',
                'value': 'self_draw',
            },
        ],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'rob_kong',
        'label': {
            'en': 'Steal Gong',
            'zh-hk': '搶槓',
            'zh-cn': '搶槓',
        },
        'kind': 'special',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [],
        'suit_conditions': [],
        'context_conditions': [
            {
                'context_field': 'win_source',
                'operator': 'equals',
                'value': 'rob_kong',
            },
        ],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'concealed_hand',
        'label': {
            'en': 'Concealed Hand',
            'zh-hk': '門清',
            'zh-cn': '門前清',
        },
        'kind': 'special',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [],
        'suit_conditions': [],
        'context_conditions': [
            {
                'context_field': 'is_open_hand',
                'operator': 'equals',
                'value': 'false',
            },
        ],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'tsumo_after_kong',
        'label': {
            'en': 'Touch Myself After Gong',
            'zh-hk': '嶺上開花',
            'zh-cn': '嶺上開花',
        },
        'kind': 'special',
        'logic_type': 'standard',
        'combine_op': 'and',
        'note': '',
        'group_conditions': [
            {
                'group_type': 'kong',
                'operator': 'at_least',
                'value_int': 1,
                'target_type': 'tile',
                'tile_code': None,
                'tile_set_code': None,
                'allow_open': True,
                'allow_closed': True,
            },
        ],
        'suit_conditions': [],
        'context_conditions': [
            {
                'context_field': 'win_source',
                'operator': 'equals',
                'value': 'self_draw',
            },
        ],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'last_tile_win',
        'label': {
            'en': 'Win by Last Tile',
            'zh-hk': '海底撈月',
            'zh-cn': '海底撈月',
        },
        'kind': 'special',
        'logic_type': 'standard',
        'combine_op': '',
        'note': 'No ContextField for last-tile win',
        'group_conditions': [],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    # --- FLOWER / SEASON BONUS ---
    {
        'code': 'own_flower',
        'label': {
            'en': 'Own Flower',
            'zh-hk': '正花',
            'zh-cn': '正花',
        },
        'kind': 'bonus',
        'logic_type': 'standard',
        'combine_op': '',
        'note': 'Requires seat-position ContextField not yet in schema',
        'group_conditions': [],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'own_season',
        'label': {
            'en': 'Own Season',
            'zh-hk': '正季',
            'zh-cn': '正季',
        },
        'kind': 'bonus',
        'logic_type': 'standard',
        'combine_op': '',
        'note': 'Requires seat-position ContextField not yet in schema',
        'group_conditions': [],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [],
    },
    {
        'code': 'all_flowers',
        'label': {
            'en': 'All Four Flowers',
            'zh-hk': '一台花',
            'zh-cn': '花槓',
        },
        'kind': 'bonus',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [
            {
                'target_type': 'tile_set',
                'tile_code': None,
                'tile_set_code': 'flowers',
                'operator': 'at_least',
                'value_int': 4,
            },
        ],
    },
    {
        'code': 'all_seasons',
        'label': {
            'en': 'All Four Seasons',
            'zh-hk': '一台季',
            'zh-cn': '季槓',
        },
        'kind': 'bonus',
        'logic_type': 'standard',
        'combine_op': '',
        'note': '',
        'group_conditions': [],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [
            {
                'target_type': 'tile_set',
                'tile_code': None,
                'tile_set_code': 'seasons',
                'operator': 'at_least',
                'value_int': 4,
            },
        ],
    },
    {
        'code': 'no_flowers',
        'label': {
            'en': 'No Flowers',
            'zh-hk': '無花',
            'zh-cn': '無花',
        },
        'kind': 'bonus',
        'logic_type': 'standard',
        'combine_op': 'and',
        'note': '',
        'group_conditions': [],
        'suit_conditions': [],
        'context_conditions': [],
        'shape_conditions': [],
        'count_conditions': [
            {
                'target_type': 'tile_set',
                'tile_code': None,
                'tile_set_code': 'flowers',
                'operator': 'not_exists',
                'value_int': 0,
            },
            {
                'target_type': 'tile_set',
                'tile_code': None,
                'tile_set_code': 'seasons',
                'operator': 'not_exists',
                'value_int': 0,
            },
        ],
    },
]


def seed_rules(apps, schema_editor):
    RuleDefinition = apps.get_model('rule', 'RuleDefinition')
    RuleLogic = apps.get_model('rule', 'RuleLogic')
    GroupCondition = apps.get_model('rule', 'GroupCondition')
    SuitCondition = apps.get_model('rule', 'SuitCondition')
    ContextCondition = apps.get_model('rule', 'ContextCondition')
    SpecialShapeCondition = apps.get_model(
        'rule', 'SpecialShapeCondition'
    )
    CountCondition = apps.get_model('rule', 'CountCondition')

    for rule in RULES:
        rd, _ = RuleDefinition.objects.update_or_create(
            code=rule['code'],
            defaults={
                'label': rule['label'],
                'kind': rule['kind'],
            },
        )
        rl, _ = RuleLogic.objects.update_or_create(
            rule_definition=rd,
            defaults={
                'logic_type': rule['logic_type'],
                'combine_op': rule['combine_op'],
                'note': rule['note'],
            },
        )
        rl.group_conditions.all().delete()
        rl.suit_conditions.all().delete()
        rl.context_conditions.all().delete()
        rl.shape_conditions.all().delete()
        rl.count_conditions.all().delete()
        for gc in rule['group_conditions']:
            GroupCondition.objects.create(rule_logic=rl, **gc)
        for sc in rule['suit_conditions']:
            SuitCondition.objects.create(rule_logic=rl, **sc)
        for cc in rule['context_conditions']:
            ContextCondition.objects.create(rule_logic=rl, **cc)
        for shc in rule['shape_conditions']:
            SpecialShapeCondition.objects.create(
                rule_logic=rl, **shc
            )
        for count_c in rule['count_conditions']:
            CountCondition.objects.create(rule_logic=rl, **count_c)


class Migration(migrations.Migration):
    dependencies = [
        ('rule', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_rules, migrations.RunPython.noop),
    ]
