# Generated by Django 5.2.11 on 2026-03-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rule", "0002_seed_rules"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ruledefinition",
            name="kind",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="rulelogic",
            name="combine_op",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddConstraint(
            model_name="rulecondition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("operator__in", ["at_least", "at_most", "exactly", "is", "none"])
                ),
                name="rule_rulecondition_operator_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulecondition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "type__in",
                        ["hand", "chow", "pung", "kong", "pair", "tile", "suit", "win"],
                    )
                ),
                name="rule_rulecondition_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulecondition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("target__isnull", True),
                    (
                        "target__in",
                        [
                            "honor",
                            "dragon",
                            "wind",
                            "red",
                            "green",
                            "white",
                            "terminal",
                            "simple",
                            "flower",
                            "bamboo",
                            "dot",
                            "character",
                            "standard",
                            "seven_pairs",
                            "thirteen_orphans",
                            "nine_gates",
                            "all_green",
                            "",
                        ],
                    ),
                    _connector="OR",
                ),
                name="rule_rulecondition_target_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulecondition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("context__isnull", True),
                    (
                        "context__in",
                        [
                            "concealed",
                            "seat_wind",
                            "round_wind",
                            "self_draw",
                            "rob_kong",
                            "replacement",
                            "double_replacement",
                            "last_tile",
                            "last_discard",
                            "heavenly",
                            "earthly",
                            "",
                        ],
                    ),
                    _connector="OR",
                ),
                name="rule_rulecondition_context_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="ruledefinition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("kind__in", ["pattern", "bonus", "limit", "special", "dora_like"])
                ),
                name="rule_ruledefinition_kind_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulelogic",
            constraint=models.CheckConstraint(
                condition=models.Q(("combine_op__in", ["and", "or", ""])),
                name="rule_rulelogic_combine_op_valid",
            ),
        ),
    ]
