# Generated by Django 5.2.11 on 2026-03-05 16:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rule", "0003_alter_ruledefinition_kind_alter_rulelogic_combine_op_and_more"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ruleset",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("country_code", models.CharField(max_length=8)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rulesets",
                        to="user.client",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="RulesetVersion",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_int", models.PositiveIntegerField()),
                ("status", models.CharField(max_length=16)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="rule.ruleset",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RulesetScoringConfig",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("scoring_unit", models.CharField(max_length=16)),
                ("min_scoring_unit", models.IntegerField(blank=True, null=True)),
                (
                    "ruleset_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_config",
                        to="rule.rulesetversion",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RulesetItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("value_int", models.IntegerField()),
                ("enabled", models.BooleanField(default=True)),
                (
                    "rule_definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ruleset_items",
                        to="rule.ruledefinition",
                    ),
                ),
                (
                    "ruleset_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="rule.rulesetversion",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="rulesetversion",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "active", "deprecated"])),
                name="rule_rulesetversion_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulesetversion",
            constraint=models.UniqueConstraint(
                fields=("ruleset", "version_int"),
                name="rule_rulesetversion_unique_version_int",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulesetscoringconfig",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("scoring_unit__in", ["faan", "han", "tai", "points"])
                ),
                name="rule_rulesetscoringconfig_scoring_unit_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulesetitem",
            constraint=models.UniqueConstraint(
                fields=("ruleset_version", "rule_definition"),
                name="rule_rulesetitem_unique_rule_per_version",
            ),
        ),
    ]
