# Generated by Django 5.2.11 on 2026-03-07 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("rule", "0005_ruleexclusion_ruleset_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ruledefinition",
            name="description",
        ),
    ]
