# Generated by Django 5.2.11 on 2026-03-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rule", "0006_remove_ruledefinition_description"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="rulecondition",
            name="rule_rulecondition_operator_valid",
        ),
        migrations.RemoveConstraint(
            model_name="rulecondition",
            name="rule_rulecondition_type_valid",
        ),
        migrations.RemoveConstraint(
            model_name="rulecondition",
            name="rule_rulecondition_target_valid",
        ),
        migrations.RemoveConstraint(
            model_name="rulecondition",
            name="rule_rulecondition_context_valid",
        ),
        migrations.AlterField(
            model_name="rulecondition",
            name="operator",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
