# Generated by Django 5.2.11 on 2026-03-08 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rule", "0008_update_seed_condition_types"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="rulecondition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("operator__isnull", True),
                    ("operator__in", ["at_least", "at_most", "exactly"]),
                    _connector="OR",
                ),
                name="rule_rulecondition_operator_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulecondition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "type__in",
                        [
                            "hand_structure",
                            "chow_count",
                            "pung_count",
                            "kong_count",
                            "pair_count",
                            "tile_count",
                            "suit_count",
                            "win_condition",
                        ],
                    )
                ),
                name="rule_rulecondition_type_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="rulecondition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("context__isnull", True),
                        ("operator__isnull", False),
                        (
                            "target__in",
                            [
                                "simple",
                                "terminal",
                                "honor",
                                "dragon",
                                "wind",
                                "red",
                                "green",
                                "white",
                                "bamboo",
                                "dot",
                                "character",
                                "flower",
                                "concealed",
                            ],
                        ),
                        (
                            "type__in",
                            [
                                "chow_count",
                                "pung_count",
                                "kong_count",
                                "pair_count",
                                "tile_count",
                            ],
                        ),
                        ("value__isnull", False),
                    ),
                    models.Q(
                        ("context__isnull", True),
                        ("operator__isnull", False),
                        ("target__isnull", True),
                        (
                            "type__in",
                            ["chow_count", "pung_count", "kong_count", "pair_count"],
                        ),
                        ("value__isnull", False),
                    ),
                    models.Q(
                        ("context__in", ["seat_wind", "round_wind"]),
                        ("operator__isnull", False),
                        (
                            "target__in",
                            [
                                "simple",
                                "terminal",
                                "honor",
                                "dragon",
                                "wind",
                                "red",
                                "green",
                                "white",
                                "bamboo",
                                "dot",
                                "character",
                                "flower",
                                "concealed",
                            ],
                        ),
                        (
                            "type__in",
                            ["chow_count", "pung_count", "kong_count", "pair_count"],
                        ),
                        ("value__isnull", False),
                    ),
                    models.Q(
                        ("context__in", ["seat_wind", "round_wind"]),
                        ("operator__isnull", False),
                        ("target__isnull", True),
                        (
                            "type__in",
                            ["chow_count", "pung_count", "kong_count", "pair_count"],
                        ),
                        ("value__isnull", False),
                    ),
                    models.Q(
                        ("context__isnull", True),
                        ("operator__isnull", True),
                        (
                            "target__in",
                            [
                                "standard",
                                "seven_pairs",
                                "thirteen_orphans",
                                "nine_gates",
                                "all_green",
                                "all_concealed",
                            ],
                        ),
                        ("type", "hand_structure"),
                        ("value__isnull", True),
                    ),
                    models.Q(
                        ("context__isnull", True),
                        ("operator__isnull", False),
                        ("target__isnull", True),
                        ("type", "suit_count"),
                        ("value__isnull", False),
                    ),
                    models.Q(
                        (
                            "context__in",
                            [
                                "self_draw",
                                "rob_kong",
                                "replacement",
                                "double_replacement",
                                "last_tile",
                                "last_discard",
                                "heavenly",
                                "earthly",
                            ],
                        ),
                        ("operator__isnull", True),
                        ("target__isnull", True),
                        ("type", "win_condition"),
                        ("value__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="rule_rulecondition_target_valid",
            ),
        ),
    ]
