# Generated by Django 5.2.11 on 2026-03-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadsession",
            name="status",
            field=models.CharField(default="created", max_length=32),
        ),
        migrations.AddConstraint(
            model_name="asset",
            constraint=models.CheckConstraint(
                condition=models.Q(("storage_provider__in", ["s3", "r2", "local"])),
                name="asset_asset_storage_provider_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="uploadsession",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["created", "presigned", "completed", "failed"])
                ),
                name="asset_uploadsession_status_valid",
            ),
        ),
    ]
