# Generated by Django 6.0 on 2025-12-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="asset",
            new_name="asset_asset_storage_7bca39_idx",
            old_name="assets_asse_storage_45caa4_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="asset_asset_checksu_591e99_idx",
            old_name="assets_asse_checksu_ab702b_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="asset_asset_created_839fef_idx",
            old_name="assets_asse_created_6d1779_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="asset_asset_exif_ca_eae4c4_idx",
            old_name="assets_asse_exif_ca_79a4d9_idx",
        ),
        migrations.RenameIndex(
            model_name="asset",
            new_name="asset_asset_is_acti_d69c24_idx",
            old_name="assets_asse_is_acti_7e009b_idx",
        ),
        migrations.RenameIndex(
            model_name="assetref",
            new_name="asset_asset_owner_c_350290_idx",
            old_name="assets_asse_owner_c_f8e9b8_idx",
        ),
        migrations.RenameIndex(
            model_name="assetref",
            new_name="asset_asset_created_62a465_idx",
            old_name="assets_asse_created_e10413_idx",
        ),
        migrations.RenameIndex(
            model_name="assetref",
            new_name="asset_asset_capture_65d292_idx",
            old_name="assets_asse_capture_c2ae44_idx",
        ),
        migrations.RenameIndex(
            model_name="uploadsession",
            new_name="asset_uploa_client__614339_idx",
            old_name="assets_uplo_client__fefb86_idx",
        ),
        migrations.RenameIndex(
            model_name="uploadsession",
            new_name="asset_uploa_status_254ad2_idx",
            old_name="assets_uplo_status_ad5514_idx",
        ),
    ]
