# Generated by Django 6.0 on 2025-12-14 06:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("user", "0002_alter_client_created_at_alter_client_install_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hand",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("camera", "CAMERA"),
                            ("manual", "MANUAL"),
                            ("import", "IMPORT"),
                        ],
                        default="camera",
                        max_length=32,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hands",
                        to="user.client",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["client", "created_at"],
                        name="hands_hand_client__4f6446_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="hands_hand_created_715e91_idx"
                    ),
                ],
            },
        ),
    ]
