# Generated by Django 6.0 on 2025-12-15 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hand", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="hand",
            new_name="hand_hand_client__7b057e_idx",
            old_name="hands_hand_client__4f6446_idx",
        ),
        migrations.RenameIndex(
            model_name="hand",
            new_name="hand_hand_created_6c2730_idx",
            old_name="hands_hand_created_715e91_idx",
        ),
    ]
