# Generated by Django 6.0 on 2025-12-17 02:31

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
        ("hand", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hand",
            name="source",
            field=models.CharField(
                choices=[
                    ("camera", "CAMERA"),
                    ("manual", "MANUAL"),
                    ("import", "IMPORT"),
                    ("other", "OTHER"),
                ],
                default="camera",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="HandDetection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "PENDING"),
                            ("running", "RUNNING"),
                            ("succeeded", "SUCCEEDED"),
                            ("failed", "FAILED"),
                        ],
                        default="pending",
                        max_length=32,
                    ),
                ),
                (
                    "model_name",
                    models.CharField(blank=True, default="", max_length=128),
                ),
                (
                    "model_version",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "confidence_overall",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=5, null=True
                    ),
                ),
                ("error_code", models.CharField(blank=True, default="", max_length=64)),
                ("error_message", models.TextField(blank=True, default="")),
                (
                    "asset_ref",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detections",
                        to="asset.assetref",
                    ),
                ),
                (
                    "hand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detections",
                        to="hand.hand",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DetectionTile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tile_code", models.CharField(max_length=8)),
                ("x1", models.IntegerField()),
                ("y1", models.IntegerField()),
                ("x2", models.IntegerField()),
                ("y2", models.IntegerField()),
                ("confidence", models.DecimalField(decimal_places=4, max_digits=5)),
                (
                    "detection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiles",
                        to="hand.handdetection",
                    ),
                ),
            ],
            options={
                "ordering": ["x1"],
            },
        ),
        migrations.AddIndex(
            model_name="handdetection",
            index=models.Index(
                fields=["hand", "created_at"], name="hand_handde_hand_id_5dd8fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="handdetection",
            index=models.Index(
                fields=["asset_ref"], name="hand_handde_asset_r_a8a740_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="handdetection",
            index=models.Index(fields=["status"], name="hand_handde_status_6133bd_idx"),
        ),
        migrations.AddIndex(
            model_name="handdetection",
            index=models.Index(
                fields=["model_version", "status"],
                name="hand_handde_model_v_cbb450_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="detectiontile",
            index=models.Index(
                fields=["detection"], name="hand_detect_detecti_0edea1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="detectiontile",
            index=models.Index(
                fields=["tile_code"], name="hand_detect_tile_co_07ac76_idx"
            ),
        ),
    ]
