# Generated by Django 6.0 on 2025-12-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hand", "0002_alter_hand_source_handdetection_detectiontile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectiontile",
            name="tile_code",
            field=models.CharField(
                choices=[
                    ("1B", "BAMBOO_1"),
                    ("2B", "BAMBOO_2"),
                    ("3B", "BAMBOO_3"),
                    ("4B", "BAMBOO_4"),
                    ("5B", "BAMBOO_5"),
                    ("6B", "BAMBOO_6"),
                    ("7B", "BAMBOO_7"),
                    ("8B", "BAMBOO_8"),
                    ("9B", "BAMBOO_9"),
                    ("1C", "CHARACTER_1"),
                    ("2C", "CHARACTER_2"),
                    ("3C", "CHARACTER_3"),
                    ("4C", "CHARACTER_4"),
                    ("5C", "CHARACTER_5"),
                    ("6C", "CHARACTER_6"),
                    ("7C", "CHARACTER_7"),
                    ("8C", "CHARACTER_8"),
                    ("9C", "CHARACTER_9"),
                    ("1D", "DOT_1"),
                    ("2D", "DOT_2"),
                    ("3D", "DOT_3"),
                    ("4D", "DOT_4"),
                    ("5D", "DOT_5"),
                    ("6D", "DOT_6"),
                    ("7D", "DOT_7"),
                    ("8D", "DOT_8"),
                    ("9D", "DOT_9"),
                    ("EW", "EAST_WIND"),
                    ("SW", "SOUTH_WIND"),
                    ("WW", "WEST_WIND"),
                    ("NW", "NORTH_WIND"),
                    ("RD", "RED_DRAGON"),
                    ("GD", "GREEN_DRAGON"),
                    ("WD", "WHITE_DRAGON"),
                    ("1F", "FLOWER_1"),
                    ("2F", "FLOWER_2"),
                    ("3F", "FLOWER_3"),
                    ("4F", "FLOWER_4"),
                    ("1S", "SEASON_1"),
                    ("2S", "SEASON_2"),
                    ("3S", "SEASON_3"),
                    ("4S", "SEASON_4"),
                ],
                max_length=8,
            ),
        ),
    ]
