# Generated by Django 6.0 on 2025-12-20 07:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hand", "0003_alter_detectiontile_tile_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="HandCorrection",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "detection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="corrections",
                        to="hand.handdetection",
                    ),
                ),
                (
                    "hand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="hand.hand",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="hand",
            name="active_hand_correction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="hand.handcorrection",
            ),
        ),
        migrations.CreateModel(
            name="HandTile",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "tile_code",
                    models.CharField(
                        choices=[
                            ("1B", "BAMBOO_1"),
                            ("2B", "BAMBOO_2"),
                            ("3B", "BAMBOO_3"),
                            ("4B", "BAMBOO_4"),
                            ("5B", "BAMBOO_5"),
                            ("6B", "BAMBOO_6"),
                            ("7B", "BAMBOO_7"),
                            ("8B", "BAMBOO_8"),
                            ("9B", "BAMBOO_9"),
                            ("1C", "CHARACTER_1"),
                            ("2C", "CHARACTER_2"),
                            ("3C", "CHARACTER_3"),
                            ("4C", "CHARACTER_4"),
                            ("5C", "CHARACTER_5"),
                            ("6C", "CHARACTER_6"),
                            ("7C", "CHARACTER_7"),
                            ("8C", "CHARACTER_8"),
                            ("9C", "CHARACTER_9"),
                            ("1D", "DOT_1"),
                            ("2D", "DOT_2"),
                            ("3D", "DOT_3"),
                            ("4D", "DOT_4"),
                            ("5D", "DOT_5"),
                            ("6D", "DOT_6"),
                            ("7D", "DOT_7"),
                            ("8D", "DOT_8"),
                            ("9D", "DOT_9"),
                            ("EW", "EAST_WIND"),
                            ("SW", "SOUTH_WIND"),
                            ("WW", "WEST_WIND"),
                            ("NW", "NORTH_WIND"),
                            ("RD", "RED_DRAGON"),
                            ("GD", "GREEN_DRAGON"),
                            ("WD", "WHITE_DRAGON"),
                            ("1F", "FLOWER_1"),
                            ("2F", "FLOWER_2"),
                            ("3F", "FLOWER_3"),
                            ("4F", "FLOWER_4"),
                            ("1S", "SEASON_1"),
                            ("2S", "SEASON_2"),
                            ("3S", "SEASON_3"),
                            ("4S", "SEASON_4"),
                        ],
                        max_length=4,
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "hand_correction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiles",
                        to="hand.handcorrection",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order"],
            },
        ),
        migrations.AddIndex(
            model_name="handcorrection",
            index=models.Index(
                fields=["hand", "created_at"], name="hand_handco_hand_id_a5ff35_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="handcorrection",
            index=models.Index(
                fields=["detection"], name="hand_handco_detecti_6e32c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="handtile",
            index=models.Index(
                fields=["hand_correction", "sort_order"],
                name="hand_handti_hand_co_0d5596_idx",
            ),
        ),
    ]
