# Generated by Django 6.0.2 on 2026-02-11 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hand", "0004_handcorrection_hand_active_hand_correction_handtile_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="handdetection",
            name="call_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
