# Generated by Django 5.2.11 on 2026-03-03 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0002_alter_uploadsession_status_and_more"),
        ("hand", "0005_handdetection_call_id"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectiontile",
            name="tile_code",
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name="hand",
            name="source",
            field=models.CharField(default="camera", max_length=32),
        ),
        migrations.AlterField(
            model_name="handdetection",
            name="status",
            field=models.CharField(default="pending", max_length=32),
        ),
        migrations.AlterField(
            model_name="handtile",
            name="tile_code",
            field=models.CharField(max_length=4),
        ),
        migrations.AddConstraint(
            model_name="detectiontile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "tile_code__in",
                        [
                            "1B",
                            "2B",
                            "3B",
                            "4B",
                            "5B",
                            "6B",
                            "7B",
                            "8B",
                            "9B",
                            "1C",
                            "2C",
                            "3C",
                            "4C",
                            "5C",
                            "6C",
                            "7C",
                            "8C",
                            "9C",
                            "1D",
                            "2D",
                            "3D",
                            "4D",
                            "5D",
                            "6D",
                            "7D",
                            "8D",
                            "9D",
                            "EW",
                            "SW",
                            "WW",
                            "NW",
                            "RD",
                            "GD",
                            "WD",
                            "1F",
                            "2F",
                            "3F",
                            "4F",
                            "1S",
                            "2S",
                            "3S",
                            "4S",
                        ],
                    )
                ),
                name="hand_detectiontile_tile_code_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="hand",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source__in", ["camera", "manual", "import", "other"])
                ),
                name="hand_hand_source_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="handdetection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["pending", "running", "succeeded", "failed"])
                ),
                name="hand_handdetection_status_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="handtile",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "tile_code__in",
                        [
                            "1B",
                            "2B",
                            "3B",
                            "4B",
                            "5B",
                            "6B",
                            "7B",
                            "8B",
                            "9B",
                            "1C",
                            "2C",
                            "3C",
                            "4C",
                            "5C",
                            "6C",
                            "7C",
                            "8C",
                            "9C",
                            "1D",
                            "2D",
                            "3D",
                            "4D",
                            "5D",
                            "6D",
                            "7D",
                            "8D",
                            "9D",
                            "EW",
                            "SW",
                            "WW",
                            "NW",
                            "RD",
                            "GD",
                            "WD",
                            "1F",
                            "2F",
                            "3F",
                            "4F",
                            "1S",
                            "2S",
                            "3S",
                            "4S",
                        ],
                    )
                ),
                name="hand_handtile_tile_code_valid",
            ),
        ),
    ]
