# Generated by Django 5.2.11 on 2026-03-06 13:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hand", "0006_alter_detectiontile_tile_code_alter_hand_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HandContext",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, editable=False
                    ),
                ),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "hand",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="context",
                        serialize=False,
                        to="hand.hand",
                    ),
                ),
                ("seat_wind", models.CharField(max_length=2)),
                ("round_wind", models.CharField(max_length=2)),
                ("win_method", models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("seat_wind__in", ["E", "S", "W", "N"])),
                        name="hand_handcontext_seat_wind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("round_wind__in", ["E", "S", "W", "N"])),
                        name="hand_handcontext_round_wind_valid",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("win_method__isnull", True),
                            ("win_method__in", ["self_draw", "discard"]),
                            _connector="OR",
                        ),
                        name="hand_handcontext_win_method_valid",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HandWinModifier",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("modifier", models.CharField(max_length=32)),
                (
                    "hand_context",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="win_modifiers",
                        to="hand.handcontext",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "modifier__in",
                                [
                                    "concealed",
                                    "rob_kong",
                                    "replacement",
                                    "double_replacement",
                                    "last_tile",
                                    "last_discard",
                                    "heavenly",
                                    "earthly",
                                ],
                            )
                        ),
                        name="hand_handwinmodifier_modifier_valid",
                    ),
                    models.UniqueConstraint(
                        fields=("hand_context", "modifier"),
                        name="hand_handwinmodifier_unique_modifier_per_context",
                    ),
                ],
            },
        ),
    ]
