# Generated by Django 5.2.11 on 2026-03-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hand", "0007_handcontext_handwinmodifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="handtile",
            name="is_concealed",
            field=models.BooleanField(default=True),
        ),
    ]
