# Generated by Django 6.0 on 2025-12-12 15:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "install_id",
                    models.CharField(
                        help_text="Anonymous install identity. Use cuid2 or ULID generated on first launch.",
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional friendly label for debugging or future UX.",
                        max_length=120,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        help_text="When this guest identity was first seen.",
                    ),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Updated whenever the app calls identify/ping.",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["last_seen_at"], name="client_last_seen_idx")
                ],
            },
        ),
    ]
