# Generated by Django 6.0 on 2025-12-15 01:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_client_created_at_alter_client_install_id_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="client",
            name="client_last_seen_idx",
        ),
        migrations.AlterField(
            model_name="client",
            name="last_seen_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
